# Game Constants
MAX_LOG_SLOTS = 6
MAX_STICKS = 3
LOGICAL_WIDTH = 1280
LOGICAL_HEIGHT = 720

# === SURVIVAL ===
MAX_BODY_TEMP = 37.0
MIN_BODY_TEMP = 30.0 # Death threshold? Or just min?
DEATH_TEMP = 0.0
HYPOTHERMIA_THRESHOLD = 32.0

# === FIRE ===
MAX_FIRE_FUEL = 120.0 # Seconds
FUEL_PER_LOG = 30.0
FUEL_PER_STICK = 5.0
FIRE_HEAT_RADIUS = 200

# === RESOURCES ===
TREE_HEALTH = 3
TREE_REGROW_TICKS_SAPLING = 50
TREE_REGROW_TICKS_FULL = 100
LOGS_PER_TREE = 3
